### ISSUE TITLE
bc.log is not working well

### ISSUE THREAD

**Issue by kharoc** [BlazingDB/blazingsql#1066]
- There is not generating RAL.0.log, I tested in a small cluster (2 workers) and I see that only generate RAL.1.log
- When I try to create a table executing 
	bc.create_table('log_table', data_dir, delimiter="|", dtype=col_dtypes, names=col_names, file_format="csv")
  and it supposed that the table was created but it was wrong. if I execute bc.describe_table('log_table') there is anything.
- So, when I want to do queries over log_table, bc.log doesn't work.

**Comment by rommelDB** [comment]
Hey, Kharo, could you please put the output for the following snippet?

import blazingsql
print(blazingsql.info())

Additionally, could you attach the complete script you tested?

**Comment by kharoc** [comment]
@rommelDB this is the output 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-58-7f7a0611b6d3> in <module>
      1 import blazingsql
----> 2 print(blazingsql.info())

AttributeError: module 'blazingsql' has no attribute 'info'
```

**Comment by romeluko** [comment]
Sorry, my bad, actually the right snippet is:

import blazingsql
print(blazingsql.__info__())

**Comment by rommelDB** [comment]
Sorry, my bad, the right snippet is:

```
import blazingsql
print(blazingsql.__info__())
```

**Comment by rommelDB** [comment]
@kharoc I see what the problem is in the notebook. So, it is not necessary to create a new log table (in your case _log_table_) because the log table is created automatically in the first call to bc.log() and its name by default is **bsql_logs**. Furthermore, the best place to configure the logging directory and its level is at the beginning of the script and not just before the call to bc.log. I think this could cause problems.
