### ISSUE TITLE
[FEA] Support string LOWER

### ISSUE THREAD

**Issue by beckernick** [BlazingDB/blazingsql#1135]
I'd like to be able to call LOWER on a string column to convert the case to lowercase. The alternative today would be to go to cudf/dask and use `str.lower()`, which can be difficult inside query logic.

```python
from pyspark.sql import SparkSession
​
spark = SparkSession.builder \
    .master("local") \
    .getOrCreate()
​
spark.sql("SELECT LOWER('Example')").show()
+--------------+
|lower(Example)|
+--------------+
|       example|
+--------------+
```

**Comment by williamBlazing** [comment]
When implementing UPPER (https://github.com/BlazingDB/blazingsql/issues/1134) and LOWER  you should look at how CHAR_LENGTH is implemented and also SUBSTRING.

With CHAR_LENGTH you can see how a unary function that takes a string input is handled, since UPPER and LOWER are both unary functions that take in a string input.
With SUBSTRING you can see how a function that outputs a string is handled

UPPER and LOWER should both be implemented with the same PR
