### ISSUE TITLE
Updating PartwiseJoin kernel to use the new task executor

### ISSUE THREAD

**Issue by jeanp413** [BlazingDB/blazingsql#1215]
This issue is to discus how we should update the PartwiseJoin kernel to use the task executor.
Currently there is blocker as the PartwiseJoin kernel uses `leftArrayCache` and `rightArrayCache` to store the left and right batches that will be joined but the task executor also keeps needs ownership of the input batches when we call `add_task`.
The simplest option would be to clone the batches.
```c++
std::vector<std::unique_ptr<ral::cache::CacheData>> inputs;
inputs.push_back(std::move(left_cache_data));
inputs.push_back(std::move(right_cache_data));

ral::execution::executor::get_instance()->add_task(
						std::move(inputs),
						this->output_cache(),
						this);

mark_set_completed(left_ind, right_ind);
```

**Comment by felipeblazing** [comment]
So one of the potential solutions to this is something as follows.

We change cachedata to be one class and have things like metadata, where its cached, or if it can be used multiple times be stored as part of the parameters it gets on initialization instead of having different class types for these things.

In this way we coud have a cachedata that could ensuer that decache is only called by one thread at a time and the others basically wait until the first one finishes and they all get the same shared_ptr back.

This means we have to change from the use of unique_ptr to shared_ptr in the task executor. This would have alot of repercussions for the code in the executor.

**Comment by williamBlazing** [comment]
One way we could do this is that every PairwiseJoin takes batches from the leftArrayCache and rightArrayCache (not cloned) and also the index for each (this would be some extra parameters that the task would need to be able to take. How we pass extra parameters we can discuss separatelly, but that is a relatively easy problem to resolve). 

That pair of batches is joined. Once the pair of batches is joined, at the end of the task these are added back to the arrayCaches.

**Comment by williamBlazing** [comment]
Note that in the proposal above, a lot of the logic that tries to reuse the batches and avoiding putting them back into cache machines if we dont need to, that logic would disappear. In that regard it would try to be less "clever"

**Comment by williamBlazing** [comment]
> So one of the potential solutions to this is something as follows.
> 
> We change cachedata to be one class and have things like metadata, where its cached, or if it can be used multiple times be stored as part of the parameters it gets on initialization instead of having different class types for these things.
> 
> In this way we coud have a cachedata that could ensuer that decache is only called by one thread at a time and the others basically wait until the first one finishes and they all get the same shared_ptr back.
> 
> This means we have to change from the use of unique_ptr to shared_ptr in the task executor. This would have alot of repercussions for the code in the executor.

This concept is very powerful, but we would need to change a lot of things. For example, if you have a shared_ptr to a CacheData, then when you decache, do you get a view or the owned object? It would have to be just a view. Now this becomes problematic for something like the Project kernel, where it wants to have ownership, so that if it wants to, it will only change one column. In order to enable that, then we would have to more heavily rely on tables that own their columns, but the columns themselves could be either owned or just views. And honestly i worry that in this mixture of owned and shared objects we are going to tie ourselves into knots....

**Comment by felipeblazing** [comment]
> > So one of the potential solutions to this is something as follows.
> > We change cachedata to be one class and have things like metadata, where its cached, or if it can be used multiple times be stored as part of the parameters it gets on initialization instead of having different class types for these things.
> > In this way we coud have a cachedata that could ensuer that decache is only called by one thread at a time and the others basically wait until the first one finishes and they all get the same shared_ptr back.
> > This means we have to change from the use of unique_ptr to shared_ptr in the task executor. This would have alot of repercussions for the code in the executor.
> 
> This concept is very powerful, but we would need to change a lot of things. For example, if you have a shared_ptr to a CacheData, then when you decache, do you get a view or the owned object? It would have to be just a view. Now this becomes problematic for something like the Project kernel, where it wants to have ownership, so that if it wants to, it will only change one column. In order to enable that, then we would have to more heavily rely on tables that own their columns, but the columns themselves could be either owned or just views. And honestly i worry that in this mixture of owned and shared objects we are going to tie ourselves into knots....

yours is way easier lets do williams thing

**Comment by williamBlazing** [comment]
@jeanp413 if you want, lets talk and I can explain what i am thinking
