### ISSUE TITLE
[BUG] RAL_EXPECTS to prevent string literals in string functions may not be executing

### ISSUE THREAD

**Issue by beckernick** [BlazingDB/blazingsql#1222]
Despite the `RAL_EXPECTS(!is_literal(arg_tokens[0]), "LIKE operator not supported for string literals");`, we can still pass string literals to string functions such as LIKE.

```python
from blazingsql import BlazingContext
import pandas as pd

bc = BlazingContext()

df = pd.DataFrame({
    "a": ["Felipe", "William", "Rodrigo"],
    "b": [10, 9, 8],
})

bc.create_table("df", df)

query = """
SELECT a
FROM df
WHERE 'hide' LIKE '%i%'
"""

print(bc.sql(query))
BlazingContext ready
         a
0   Felipe
1  William
2  Rodrigo
```

The RAL_EXPECTS message does not appear as output. Adding some couts to see what's happening:
```
case operator_type::BLZ_STR_LIKE:
    {
        assert(arg_tokens.size() == 2);
        std::cout << arg_tokens[0] << "\n";
        std::cout << is_literal(arg_tokens[0]) << "\n";
        RAL_EXPECTS(!is_literal(arg_tokens[0]), "LIKE operator not supported for string literals");
...
```

The output from std::cout when we pass a column is:
```
$0
0
$0
0
```

But when we pass the string 'hide', there is no output from the couts.

**Comment by williamBlazing** [comment]
@beckernick We want to add those RAL_EXPECTS statements as appropriate, because the engine does not support that. The reason you are not seeing it is that most of the time Apache Calcite will evaluate operations on literals for us. So that by the time the relational algebra arrives to the engine itself, the engine does not have to deal with it.

In the example you stated above, you can see it by doing `bc.explain(query)` which in this case returns:
```
>>> bc.explain(query)
'BindableTableScan(table=[[main, df]], projects=[[0]], aliases=[[a]])\n'
```
