### ISSUE TITLE
[FEA] Support numpy>=1.20

### ISSUE THREAD

**Issue by randerzander** [BlazingDB/blazingsql#1432]
Related to [cudf #7289](https://github.com/rapidsai/cudf/issues/7289).

BlazingSQL [seems to require `numpy=1.19`](https://github.com/BlazingDB/blazingsql/blob/9438e474f8a6b817a04db2ae41a6e0b2315cf0f3/ci/gpu/build.sh#L57) which breaks dask-cudf's `describe` functionality.

Is numpy 1.19 a hard requirement for BlazingSQL?

**Comment by romulo-auccapuclla** [comment]
@randerzander thanks for open this issue, regarding numpy=1.19 is not a hard requirement for BlazingSQL because its rely's on cudf libraries. Currently we are working to update some dependencies which will install numpy=1.20.2 in this PR https://github.com/BlazingDB/blazingsql/pull/1430, meanwhile you can build from source branch-0.19 with the following steps:

`conda create --yes -n bsql python=3.8`

`conda activate bsql`

`conda install --yes -c conda-forge spdlog=1.7.0 google-cloud-cpp=1.25.0 ninja tqdm mysql-connector-cpp=8.0.23 libpq=13 sqlite=3 nlohmann_json`

`conda install --yes -c rapidsai-nightly -c nvidia -c conda-forge -c defaults dask-cuda=0.19 dask-cudf=0.19 ucx-py=0.19 ucx-proc=*=gpu cudf=0.19 python=3.8 cudatoolkit=10.2`

`conda install --yes -c conda-forge cmake=3.18 gtest==1.10.0=h0efe328_4 gmock cppzmq cython=0.29 openjdk=8.0 maven jpype1 netifaces pyhive tqdm ipywidgets`

`./build.sh -t disable-google-gs`

**Comment by williamBlazing** [comment]
resolved
