### ISSUE TITLE
[BUG] Erroneous results with use of "<>" in the query

### ISSUE THREAD

**Issue by mlahir1** [BlazingDB/blazingsql#173]
Erroneous results with use of "<>" in the query

**Steps/Code to reproduce bug**
```
>>> bc.create_table('tbl', df)
<pyblazing.apiv2.context.BlazingTable object at 0x7f7c4969cb90>
>>> df
   a    b
0  0  1.5
1  1  1.5
2  0  1.5
3  1  1.5
4  0  1.5
5  1  1.5
6  0  1.5
7  1  1.5
8  0  1.5
9  1  1.5
>>> bc.sql('SELECT CASE WHEN a <> 1 THEN 0 ELSE b END as s, a, b from tbl')
30956
               s  a    b
0   0.000000e+00  0  1.5
1  4.940656e-324  1  1.5
2   0.000000e+00  0  1.5
3  4.940656e-324  1  1.5
4   0.000000e+00  0  1.5
5  4.940656e-324  1  1.5
6   0.000000e+00  0  1.5
7  4.940656e-324  1  1.5
8   0.000000e+00  0  1.5
9  4.940656e-324  1  1.5
>>> bc.sql('SELECT CASE WHEN a <> 1 THEN 0 ELSE b END as s, a, b from tbl').s.sum()
30956
2.5e-323
>>> int(bc.sql('SELECT CASE WHEN a <> 1 THEN 0 ELSE b END as s, a, b from tbl').s.sum())
30956
0

```
**Expected behavior**
```
>>> df =cudf.DataFrame()
>>> df['a'] = [i%2 for i in range(10)]
>>> df['b'] = 1.5
>>> df.b.sum()
15.0
>>> df[df.a == 1]['b'].sum()
7.5
>>> df
   a    b
0  0  1.5
1  1  1.5
2  0  1.5
3  1  1.5
4  0  1.5
5  1  1.5
6  0  1.5
7  1  1.5
8  0  1.5
9  1  1.5
>>> int(df[df.a == 1]['b'].sum())
7
```

*When I am using the actual data I also see some NaN's in the resulting query. But the input rows doesn't have any NaN's.

**Comment by williamBlazing** [comment]
I suspect the issue is not that <> is not working properly, but instead its an issue of type inference.
I think in the case of:
`SELECT CASE WHEN a <> 1 THEN 0 ELSE b END as s, a, b from tbl`
`a` and `1` are being interpreted as floats because `b` is a float. So when `a=1`  => `a<>1` should be false, but because its treating them both as float, float equality is not trustworthy. The cast of an INT to a FLOAT can be imprecise and you can end up with 1.000000 <> 1.000000

So I think the fix should be that the type inference of `1` in `a <> 1` should be interpreted as an INT because it has nothing to do with `b` (which is float)
