### ISSUE TITLE
[BUG] Encountered "LIKE \"" at line 1, column 140.

### ISSUE THREAD

**Issue by AETDDraper** [BlazingDB/blazingsql#197]
**Describe the bug**
SQL statement
result = bc.sql('SELECT Subject, StaffCode, count(StaffCode) as count_ent, sum(Periods) as sum_periods, sum(Minutes) FROM main.Subjecttable WHERE StaffCode LIKE"%SDR"')

The column is a three-digit name code with no Integers but could possibly be blank. 

**Expected behavior**
Should filter out the columns matching SDR

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   CONDA INSTALL

**Environment details**
Please run and paste the output of the `print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**----For BlazingSQL Developers----**
**Suspected source of the issue**
Where and what are potential sources of the issue

**Other design considerations**
What components of the engine could be affected by this?

**Comment by williamBlazing** [comment]
@AETDDraper Right now we are in the middle of migrating and refactoring our codebase to libcudf++ which is for cudf v0.12. If you are not familiar, libcudf++ is what we are calling the overhaul of cudf where all the key data structures have changed and hence most of the code of cudf. We are in the middle of migrating our code to now work with the new data structures and APIs. Its a bit of a long process, but the end result is looking beautiful. The new cudf is a great improvement and is really simplifying our codebase. Part of that cudf refactor is a completely new way of representing strings.  This means that if we fix the LIKE issue you are presenting may be a moot point in the face of this migration, since the migration may fix the issue itself. 
Additionally, I have not been able to replicate the issue.
If you find that this issue is really pressing, then perhaps you can send me a jupyter notebook with data to help me replicate this, or we can do a Live Debugging session. If its not too pressing, then please try this out again once the code migration is complete. Thanks!

**Comment by williamBlazing** [comment]
@AETDDraper We have finished our migation and refactoring to libcudf++. Which means the underlying code that handles LIKE is new and likely this issue is no longer present. I will be closing this issue at this point. If you find that with out latest blazingsql-nightly  build (https://github.com/BlazingDB/blazingsql/#nightly-version) you are still experiencing this issue, please feel free to re-open the issue and we will look into it
