### ISSUE TITLE
[BUG]BlazingSQL requires JVM.  Never mentioned as a prerequisite, nor is it installed

### ISSUE THREAD

**Issue by taureandyernv** [BlazingDB/blazingsql#235]
## Report incorrect documentation

**Location of incorrect documentation**
https://blazingsql.com/getstarted

**Describe the problems or issues found in the documentation**
the user needs to install JRE (Java) as a dependency for BlazingSQL to work.  It is not a listed dependency, nor is java installed in the install command

**Steps taken to verify documentation is incorrect**
Tried it out on RAPIDS docker container

**Suggested fix for documentation**
Add on the `getting started` page that the user needs to install Java, onto their system, like JRE or JDK

**Comment by roaramburu** [comment]
Hey @taureandyernv,

How did you install BSQL on the RAPIDS container? Did you build from Source?

Java is an internal dependency, which is why it's included in our containers and as a dependency in Conda for Conda installs. There are numerous internal dependencies, and we don't want to list them all out, as it will confuse many users.

Let me know how you installed it please so we can further understand.

**Comment by roaramburu** [comment]
Hey @taureandyernv,

We're going to be adding an internal dependencies page into our docs that will help map all of this out for advanced users. @williamBlazing will be spearheading that when he has a moment.

Thanks for bringing this to our attention!
