### ISSUE TITLE
Non-AWS s3 connection 

### ISSUE THREAD

**Issue by zackosmacko32** [BlazingDB/blazingsql#242]
**Is your feature request related to a problem? Please describe.**
Requesting additional plugin to connect to non-aws s3 file store. 

**Describe the solution you'd like**
Parameter within the s3 function to enter non-aws s3 URL

**Comment by felipeblazing** [comment]
@aucahuasi I am looking over how the file systems manage credentials and I see that we are sending them around like this 

```
	const auto credentials = Aws::Auth::AWSCredentials(accessKeyId, secretKey, sessionToken);
	const RegionResult regionResult = getRegion(bucketName, credentials);
```

We could change this so that instead we store a shared_ptr that we can make null in the case that credentials were not sent like when a user is using a public bucket. This combined with the update we made to the new SDK should resolve the issues above.

**Comment by aucahuasi** [comment]
@zackosmacko32 This PR https://github.com/BlazingDB/blazingsql/pull/524 allows non AWS S2 connections, so we can close this issues as soon as you confirm is working fine!

**Comment by zackosmacko32** [comment]
Confirmed!

[cid:image001.png@01D612F8.4D6A2680]
Zachary Fragoso
Manager – Data Science & AI
248.880.8926
