### ISSUE TITLE
Fix double read on hdfs / s3 i/o

### ISSUE THREAD

**Issue by felipeblazing** [BlazingDB/blazingsql#362]
https://github.com/BlazingDB/blazingsql/pull/176/files

This PR was meant to fix this and it got left by the wayside.  We need to pick it back up for the new versions. It should give us very significant performance improvements.

**Comment by williamBlazing** [comment]
This PR does not seem all that useful. This is all about re-using the data_handle object from when you parse the schema to when you actually do your parsing. The only thing you are re-using is the arrow::io::RandomAccessFile object. And since when you parse the schema you are only looking at the first file, then you are only reusing this for the first file.
