### ISSUE TITLE
Remove Project Copies

### ISSUE THREAD

**Issue by williamBlazing** [BlazingDB/blazingsql#380]
The project step requires that some columns be renamed or reused from the input so that they are not copied, and other columns be new. This requires that the input table be a mutable table, which is not a concept that is currently supported with BlazingTable and BlazingTableView. Not ony that, but currently we have a system where every relational algebra step returns both a BlazingTable and BlazingTableView as a pair, out of a necesity since data loaders can return a BlazingTableView (GDFLoader) or a BlazingTable (file based loaders). I think we can fix both problems by implementing something that like a BlazingTable that can internally just be a view, and/or also have mutable BlazingTable. 

This feature needs some additional design

**Comment by williamBlazing** [comment]
I propose the following solution. 
We maintain the same two objects `BlazingTable` and `BlazingTableView` but with some changes.
The `BlazingTable` class gets modified, so that internally it can either own the data (internally it has a `CudfTable`) or it does not (it only has a `CudfTableView`). Then for each of its few methods, it checks if it owns the data or not and acts accordingly.  Since there are few methods to `BlazingTable`. This seems like it would be simple enough to implement.

Then in the actual usage, we would no longer return from relational algebra step funcitons a pair of BlazingTable and BlazingTableView, we just return a BlazingTable.

Additionally, functions that could benefit from being able to take in a mutable BlazingTable, we pass in the BlazingTable with move and we can make changes is necessary. 
Functions that could benefit from taking in a BlazingTable are:
process_project (some projections are not transformations, so we want to avoid a copy)
process_union  (sometimes we are concatenating an emtpy table with a table with data. We want to be able to just return the original table)
concat_tables (sometimes we are concatenating an emtpy table with a table with data. We want to be able to just return the original table)
sort_table (we could introduce a check to see if a table is sorted already, and if it is, we save ourselves an allocation)

**Comment by felipeblazing** [comment]
> Then for each of its few methods, it checks if it owns the data or not and acts accordingly

This to me seems fraught with risk. It requires a developer to remember that every time an operation is performed or a method is called on a blazing table that they check which of these two objects is valid. We are already using unique_ptr so there really is very little downside to run time polymorphism here.

First the change must be at the level of the column not that of the table. Our tables can be mixtures of columns some of which are views into columns elswehere and others which were generated for the explicit purpose of the code they are about to run. 

something like 
```
select a, a + b ... 
```
To really handle this properly we should probably not rely on cudf_table as such and rather operate on a columnar basis and generate tableviews and decompose tables as they come into and out of operations. 


I think something like BlazingTable is something which has
```
std::vector<std::string> names;
std::vector<std::unique_ptr<BlazingColumn>> columns;
```

BlazingColumn could have two implementations BlazingColumnView, BlazingColumnOwner . Whenever we need to run a cudf function we send it a CudfTableView(vector<ColumnView>) as the inputs to whatever function we are calling. Since each implementation has the same methods none of the business logic anywhere has to change and its really just at instantiation that we know what kind of thing we are holding onto.

**Comment by felipeblazing** [comment]
I prefer runtime polymorphism because I feel it requires less effort on the part of the developer to keep consistent. Its very cumbersome when  you have to check state variables to see which execution path you can follow when you can just have method which will return your anticipated result regardless of how it does that.

**Comment by williamBlazing** [comment]
Ok, so I think I agree with you suggestion. So the polymorphism is not that there are different implementations of BlazingTable, there is a single implementation of BlazingTable, but BlazingTable does not have either a CudfTable or a CudfTableView, it instead has a collection of BlazingColumn which internally either are Owning or non-owning. 

I imagine then in the engine, we would still have BlazingTableView and BlazingTable. And BlazingTable is always a unique_ptr and we can use it as a mutable object when it makes sense.
BlazingTableView can still be the same as before.

And in BlazingTable, the only tricky function to reimplement would be std::unique_ptr<CudfTable> releaseCudfTable(). Here we would have to see which of all the BlazingColumns are non-owning, and if there are any that are non-owning, we would have to clone them, so that we can return a fully owning CudfTable

**Comment by aucahuasi** [comment]
Just a brief comment here @jeanp413 suggested we can use always the pointer to table and just pass that over all the query execution pipeline. I like this idea and may be somewhat related with the issues here, but the only drawback I see is for cases when we create a table from in-memory data sources (e.g. cudf.DataFrame, arrow etc)
