### ISSUE TITLE
[QST] What is about Used-Defined Functions (UDF)

### ISSUE THREAD

**Issue by schernolyas** [BlazingDB/blazingsql#556]
Hi!

Can I create own function for using at SQL. I mean UDF. How I can make it?

**Comment by felipeblazing** [comment]
If you want to commit directly to the engine you could do that. Depending on what kind of operation you want to make there different paths. If your intention is to add something like a UDF that operates row by row 

e.g.

gravitational_pull = func(mass_1,mass_2,distance)

I understand this example is a bit contrived because this can be expressed in terms of simple arithmetic expressions but lets pretend for a minute it couldn't and you needed to write a new function. 

You would need to compose that function into unary and binary operations.  Assuming one of those binary operators was not implemented you would need to implement it here:

https://github.com/BlazingDB/blazingsql/blob/branch-0.14/engine/src/Interpreter/interpreter_ops.cuh#L461

After doing this you would need to recompile the engine and you would be halfway there :).

The other part is that you would need to modify calcite in order for the parser to be able to parse this properly.  https://calcite.apache.org/docs/adapter.html#extensibility Gives you an idea of how to do that and this part of the code is located in

https://github.com/BlazingDB/blazingsql/tree/branch-0.14/algebra

If it can be composed into binary and unary operations that are already implemented then I really recommend just doing that in SQL. If you need operators that are not supported then it is a bit more involved.

**Comment by williamBlazing** [comment]
Hello @schernolyas , what @felipeblazing is refering to is to create and add permanently new functions in the SQL engine. For a traditional UDF, we do not currently have support. What we recommend is to use cuDF and dask to try to achieve whatever you need.

**Comment by schernolyas** [comment]
Hi @williamBlazing !

Yes, I have understood it. Thank you very much!
