### ISSUE TITLE
cUML not available in stable release[QST]

### ISSUE THREAD

**Issue by A1996KASH** [BlazingDB/blazingsql#819]
I am trying to use cUML from welcome notebook but it is not available.

**Comment by gumdropsteve** [comment]
Hi @A1996KASH, how are you running the Notebook? And can you please share the error output or steps/code to reproduce bug?

You are referring to [welcome.ipynb](https://github.com/BlazingDB/Welcome_to_BlazingSQL_Notebooks/blob/branch-0.15/welcome.ipynb), yes? If so you can run it with 0.14 and a free GPU in the [BlazingSQL Notebooks webapp](https://app.blazingsql.com/jupyter/user-redirect/lab/workspaces/auto-b/tree/Welcome_to_BlazingSQL_Notebooks/welcome.ipynb) (no setup required).

**Please note**: cuML is not downloaded with BlazingSQL because it is a separate package, and BlazingSQL is not dependant on cuML ([BlazingSQL dependencies list here](https://github.com/BlazingDB/blazingsql/network/dependencies)). You can find the conda or Docker install script for cuML with the [RAPIDS Release Selector](https://rapids.ai/start.html) or checkout the [cuML repository](https://github.com/rapidsai/cuml) for more. Thanks.

**Comment by A1996KASH** [comment]
Thanks I got it. It's not available with blazingsql only cudf is available.
