### ISSUE TITLE
[BUG] No Error When Fail to Find File

### ISSUE THREAD

**Issue by roaramburu** [BlazingDB/blazingsql#946]
**Describe the bug**
This might be a feature request, but `bc.create_table()` does not throw an error or exception when it cannot find the table.

**Steps/Code to reproduce bug**
![image](https://user-images.githubusercontent.com/5353722/90274509-54242580-de26-11ea-80e5-383aad2d0892.png)

I changed up the name of a file I had at the end with fake information and it looks like it works, but any SQL query will fail if I try to run it on that table.

**Expected behavior**
I would like it to throw a file not found error when that is the case.

**Environment overview (please complete the following information)**
BSQL Notebooks RAPIDS Stable

**----For BlazingSQL Developers----**
**Suspected source of the issue**
Where and what are potential sources of the issue

**Other design considerations**
What components of the engine could be affected by this?

**Comment by williamBlazing** [comment]
There are several things to be taken into consideration when testing and implementing fixes for this. 
What is the file type and what is the extension? And related to this are you passing in a parameter related to a file extension (`file_format` parameter for `create_table`)?

Depending on the inferred file type, it may or may not thow an error for files not found. I am assuming that for parquet files it will, since it has to get the metadata. But I'm guessing that for CSV files it will not. 

It's properly for the file types where it is not currently checking for the existence of the files we should have a function that checks for the existence of the files. This checking of the existence of the files will need to be done on the C++ side because depending on the file system being used you may not be able to do it on the python side. Additionally using task and if you have multiple files this checking for the existence of files should be done in a distributed manner. i.e. If you have 1000 files and 10 nodes then each node should check 100 files.
