### ISSUE TITLE
Google drive support for blazingsql notebooks

### ISSUE THREAD

**Issue by sreekarreddy21** [BlazingDB/blazingsql#995]
I would like to import .csv files from my google drive. Is there any way to import files apart from uploading and using s3 buckets? If we have this feature available, could you please point me to it or some kind of documentation? 

Thanks.

**Comment by felipeblazing** [comment]
S3, HDFS, GCS are supported as storage technologies. For google drive support you could do something along the lines of the instructions found here to mount google drive on linux. https://www.techrepublic.com/article/how-to-mount-your-google-drive-on-linux-with-google-drive-ocamlfuse/

**Comment by sreekarreddy21** [comment]
I could only install it as a  "root user" on app.blazingsql.com. When I logged in using Gmail, it didn't ask me to set a root password. I'm trying to figure out how to install it. Could you please help?  Thanks.

**Comment by roaramburu** [comment]
Hey @sreekarreddy21 this is a great idea, we'll look into a solution for this, but we won't be supporting this for some time. For now you'll need to bring those datasets over.

**Comment by felipeblazing** [comment]
Basically after some digging we would need a way to be able to provision users ports to the outside world so that you could handle the oauth process. This is something that could get pretty dangerous so it will be a while before we can figure out how to do this securely. 

Perhaps https://github.com/jupyterlab/jupyterlab-google-drive has a better way of doing this.

**Comment by sreekarreddy21** [comment]
Thanks.  I will upload the data for now.

**Comment by williamBlazing** [comment]
Closing, since this issue relates to app.blazingsql.com
